theme: jekyll-theme-minimal
title: Eliot's homepage
description: So far this only contains the practical part of my Master's thesis, which is a Svelte project for the interactive construction and visualisation of decision trees.
